export const PX_TO_VIEWPORT_CONFIG_KEY = '__PX_TO_VIEWPORT_CONFIG'
export const FILTER_CONFIG_KEY = '__FILTER_CONFIG'
export const REPLACE_CONFIG_KEY = '__REPLACE_CONFIG_KEY'

export const CONFIG_URL = '__CONFIG_URL'
